### ISSUE TITLE
Month returning August as "aug" instead of "Aug"

### ISSUE THREAD

**Issue by EricOyler** [noahcooper/SimpleDateFormatJS#3]
I was utilizing the simpleDateFormat method in the luminateExtend.js tool, and for some reason, August dates are the only month that return the three letter abbreviation of the month name in all lowercase. I was using this:
luminateExtend.utils.simpleDateFormat(this.event_date, 'MMM d, yyyy')
And the following demonstrates the problem:
luminateExtend.utils.simpleDateFormat(new Date('2016-08-27'), 'MMM d, yyyy');
returns:
aug 26, 2016
Other months, like September, return a captialized three-letter abbreviation of the month, ie. "Sep 10, 2016".

I am using the latest version of luminateExtend.js from the CDN.

**Comment by noahcooper** [comment]
Fixed in v1.4.
